const actionTypes = {
  SIGNIN_REQUEST: 'SIGNIN_REQUEST',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',

  LOGOUT: 'LOGOUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

  CHECK_AUTHORIZATION: 'CHECK_AUTHORIZATION',
  AUTH_LOADING: 'AUTH_LOADING',
  AUTH_ERROR: 'AUTH_ERROR',

  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SOCIAL_LOGIN: 'SOCIAL_LOGIN'
};

export default actionTypes;
