const userTypes = {
  // EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
  // SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGNIN_REQUEST: 'SIGNIN_REQUEST',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_ERROR: 'SIGNIN_ERROR',

  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
};

export default userTypes;
