// const userTypes = {
//   // EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
//   // SET_CURRENT_USER: 'SET_CURRENT_USER',
//   // SIGNIN_REQUEST: 'SIGNIN_REQUEST',
//   // SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
//   // SIGNIN_ERROR: 'SIGNIN_ERROR',

//   // SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
//   // SIGNUP_ERROR: 'SIGNUP_ERROR',

//   SIGNIN_USER: 'SIGNIN_USER',
//   SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
//   SIGNIN_FAIL: 'SIGNIN_FAIL',

//   SET_ALERT: 'SET_ALERT',
//   RESET_ALERT: 'RESET_ALERT',
// };

// export default userTypes;

export const SIGNIN_USER = 'SIGNIN_USER'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'